# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
#variables:
#  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
#
#stages:
#  - build
#  - test
#  - sonar
##  - docker-build
#  - deploy
#
#build:
#  stage: build
#  script:
#    - ./gradlew assemble
#  artifacts:
#    paths:
#      - build/classes
#      - build/libs
#    expire_in: 1h
#
#test:
#  stage: test
#  script:
#    - ./gradlew test
#  artifacts:
#    paths:
#      - build/reports/jacoco/test/jacocoTestReport.xml
#
#sonar:
#  stage: sonar
##  image: gradle:7.5-jdk17
#  script:
#    - ./gradlew sonar "-Dsonar.projectKey=habit_tracker_be" "-Dsonar.host.url=http://localhost:9000" "-Dsonar.token=$SONAR_TOKEN_MAC"
#  allow_failure: true
#  dependencies:
#    - build
#    - test
#
##docker-build:
##  stage: docker-build
##  script:
##    - docker rmi -f habit_tracker_be:latest|| true
##    - docker rm -f habit_tracker_be || true
##    - docker build -t habit_tracker_be:latest .
##    - docker run -d --name habit_tracker_be -p 8080:8080 habit_tracker_be:latest
##  only:
##    - main
##  dependencies:
##    - build
##    - test
#
##eb-deploy:
##  stage: deploy
##  only:
##    - main
##  script:
##    - zip -r app.zip . -x ".git/*" "build/*"
##    - aws elasticbeanstalk create-application-version \
##      --application-name habit-tracker-be \
##      --version-label $CI_COMMIT_SHORT_SHA \
##      --source-bundle S3Bucket=$EB_BUCKET,S3Key=app-$CI_COMMIT_SHORT_SHA.zip
##    - aws elasticbeanstalk update-environment \
##      --environment-name habit-tracker-be-env \
##      --version-label $CI_COMMIT_SHORT_SHA
#
#docker-ecr-deploy:
#  stage: deploy
#  script:
#    - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ECR_URI
#
##    - docker build -t habit-tracker-backend .
#    - docker build --platform linux/amd64 -t habit-tracker-backend .
#    - docker tag habit-tracker-backend:latest $AWS_ECR_URI:latest
#    - docker push $AWS_ECR_URI:latest
#
#    - zip deploy.zip Dockerrun.aws.json
#    - aws s3 cp deploy.zip s3://$EB_S3_BUCKET/deploy.zip
#
#    - aws elasticbeanstalk create-application-version --application-name habit-tracker-be --version-label $CI_COMMIT_SHA --source-bundle S3Bucket=$EB_S3_BUCKET,S3Key=deploy.zip
#
#    - aws elasticbeanstalk update-environment --environment-name habit-tracker-be-docker-ecr-env --version-label $CI_COMMIT_SHA
#  only:
#    - main