CREATE TABLE `users` (
    id  BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name   VARCHAR(20) NOT NULL,
    email   VARCHAR(80) NOT NULL UNIQUE,
    password    VARCHAR(255) NOT NULL,
    is_admin    BOOLEAN  NOT NULL
);