#stages:
#  - build
#  - test
#  # - lint
#  # - docker-build
#  - deploy
#
#cache:
#  key: ${CI_COMMIT_REF_SLUG}
#  paths:
#    - node_modules/
#
#build:
#  stage: build
#  script:
#    - echo "Installing dependencies..."
#    - echo "VITE_BASE_API_URL=$VITE_BASE_API_URL"
#    - npm install
#    - echo "Building project..."
#    - export VITE_BASE_API_URL=$VITE_BASE_API_URL
#    - npm run build
#    # - VITE_BASE_API_URL=$VITE_BASE_API_URL npm run build
#    # - npm run build
#  artifacts:
#    paths:
#      - build/
#      - dist/
#
#test:
#  stage: test
#  script:
#    - echo "Running tests..."
#    - npm run test -- --run --coverage
#  artifacts:
#    when: always
#    paths:
#      - coverage/
#  dependencies:
#    - build
#
## lint:
##   stage: lint
##   script:
##     - echo "Installing dependencies..."
##     - npm install
##     - echo "Running ESLint..."
##     - npm run lint
##   allow_failure: false
#
## docker-build:
##   stage: docker-build
##   script:
##     - docker rmi -f habit_tracker_fe:$CI_COMMIT_SHORT_SHA || true
##     - docker rm -f habit_tracker_fe || true    
##     - docker build -t habit_tracker_fe:$CI_COMMIT_SHORT_SHA .
##     - docker run -d --name habit_tracker_fe -p 3000:80 habit_tracker_fe:$CI_COMMIT_SHORT_SHA
##   only:
##     - main
##   dependencies:
##     - build
##     - test
#
#s3-deploy:
#  stage: deploy
#  only:
#    - main
#  script:
#    - aws s3 sync dist/ s3://$S3_BUCKET --delete